run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
  # include test files or not, default is true
  tests: false

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - lll
    - path: mockdata
      linters:
        - gomnd
        - dupl
    - path: errors
      linters:
        - gomnd

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gocognit
    - godox
    - maligned
    - prealloc
    - wsl
    - godot
    - nestif
    - gomodguard
    - asciicheck
    - goerr113
    - testpackage
    - gochecknoglobals
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gofumpt
    - goheader
    - makezero
    - nlreturn
    - noctx
    - paralleltest
    - sqlclosecheck
    - thelper
    - tparallel
    - wrapcheck
    - predeclared

    # don't enable:
    # - nolintlint
    # - exhaustivestruct

